.github/workflows/build.yml
This PR will make it so that the CI *does not* run when the `README.md` and possibly other explicitly added files are changed. See #95.
=> Do not run CI on every change.

CMakeLists.txt, benchmarks/blake.cc, benchmarks/chacha20.cc, mach
This needs cleanup and better integration. It's only a basic setup to show how it is supposed to work.
#15 #36
=> Basic setup for benchmarks

.github/workflows/coverage.yml, CMakeLists.txt, README.md, mach, tools/coverage.sh, tools/test.py, tools/utils.py
This PR introduces a workflow to measure test coverage. It adds the `--coverage` flag to the `mach build` and `mach test` subcommands and sets the clang parameters accordingly. When `mach test --coverage` is run, a html report is generated at `build/Debug/coverage/<test>/html/index.html` that can be viewed with a browser. Furthermore, it adds a job "coverage" to integrate with Coveralls.io and show if a PR increases or decreases test coverage.
Note: This PR fails CI on some systems due to the added check in [618f1b4](https://github.com/cryspen/hacl-packages/pull/110/commits/618f1b4c30733fec29216332cba1c7b0a55cd6d6). To make CI pass we need to agree how to detect the compiler in mach first. There are multiple solutions described below.
=> Add workflow to measure coverage.

docs/src/developers/ci.md, docs/src/hacl-c/evercrypt-hashing.md, docs/src/hacl-c/hacl-hashing.md
The first commit adds content to the "Continuous Integration" HACL Packages book and briefly describes the HACL Packages CI, which files are skipped, how to skip CI by using a marker in the commit message, and what platforms are covered (from a CI point of view).
The second commit fixes two typos "Hasing" --> "Hashing".
=> docs: Document CI and fix typos.

config/config.json, tests/README.md, tests/md5.cc, tests/md5/cryspen_md5.json, tests/md5/rfc1321.json
This PR adds tests for the `Hacl_Hash_MD5_legacy_hash` function. The function `Hacl_Hash_Core_MD5_legacy_init` is not covered.
=> tests: Extend md5 tests.

rust/hacl-rust-sys/build.rs, rust/src/digest.rs, rust/src/hmac.rs, rust/src/rsa_pss.rs
- remove some deprecated functions
- make the crate usable as git dependency
- implement `try_from` for `KeySize` in RsaPss
=> Minor Rust update

tests/rsapss.cc
This PR adds tests to see if `Hacl_RSAPSS_new_rsapss_load_skey` and `Hacl_RSAPSS_new_rsapss_load_pkey` accept bad keys and that signing and verification error out on a bad hash function parameter.
This PR should also serve as a test if the integration with Coveralls.io works as expected.
=> tests: Extend rsapss tests.

.github/workflows/build.yml, .github/workflows/build_pull_request.yml
This PR removes `fail-fast: false` from all `strategy` configurations. With this in place, a failing job in, e.g., the linux matrix will cancel all other jobs in that matrix. Furthermore, it splits-off a "reduced" workflof from the main "build" workflow. The reduced version only tests against the newest compilers. Furthermore, it uses Ubuntu 22.04. The review should be easiest by diffing `build.yml` and 'build_pull_request.yml'.
This partially addresses #133.
=> ci: Improve PR workflow by reducing jobs and failing fast.

tests/x25519.cc
This PR fixes `TEST(x25519Test, HaclTest)` by calling ...
```
hacl_init_cpu_features();
EverCrypt_AutoConfig2_init();
```
Without this initialization the call to `vale_x25519_support()` always returns false and `Hacl_Curve25519_64_ecdh()` is never executed.
=> tests: Extend/Fix curve25519 tests.

config/config.json, tests/evercrypt.cc, tests/evercrypt.h
This PR adds tests to check if `EverCrypt_AutoConfig2_disable_*` results in `EverCrypt_AutoConfig2_has_*` being false. Furthermore, it introduces an `EverCryptSuite<T>`. This Suite can be used in combination with `::testing::Combine(...)` to generate tuples of `(EverCryptConfig, TestCase)` to apply a specific EverCrypt configuration, i.e., "what is disabled", before every test.
=> tests: Add EverCrypt_AutoConfig2 tests and EverCrypt helpers.

CMakeLists.txt
Sorry for the back and forth. I somehow missed the `--tests` parameter when testing on my local machine. With `--tests` I get ...
```
CMake Error at /usr/share/cmake-3.22/Modules/ExternalProject.cmake:2806 (message):
At least one entry of URL is a path (invalid in a list)
```
CI has a newer version of cmake and seems to be happy.
With this PR everything should work again.
=> build(cmake): Fix DOWNLOAD_EXTRACT_TIMESTAMP, again.

CMakeLists.txt
`add_compile_options` is only picked up by targets that are defined after the options were added.
This should fix the issue that coverage for vectorised code has not been measured.
=> add compile options for all targets

CMakeLists.txt, config/toolchain.cmake, tools/ocaml.py
Looks like there are some oddities in the linux assembly that doesn't work here, i.e. ensuring the input stack is usable. The mingw version appears to have the necessary pieces.
=> windows clang-cl assembly

.github/workflows/ocaml.yml, CMakeLists.txt, ocaml/Makefile, ocaml/hacl-star-raw.opam
- use simple sed regex for bsd sed
- disable arm32 for now for the hacl-star-raw package
- https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/36ce9625967f4500f987edb78364b9ae57340696/variant/distributions,debian-10,hacl-star-raw.0.5.0
- https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/36ce9625967f4500f987edb78364b9ae57340696/variant/distributions,ubuntu-18.04,hacl-star-raw.0.5.0
- https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/36ce9625967f4500f987edb78364b9ae57340696/variant/extras,s390x,hacl-star-raw.0.5.0
=> opam fixes for 0.5.0

docs/reference/evercrypt/index.md, docs/reference/evercrypt/mac/index.md, docs/reference/hacl/mac/index.md
This PR adds documentation for HMAC (HACL + EverCrypt).
I am not sure about the recommended key sizes, though. Do we want to make a recommendation at all? Or do we want to explain key sizes for HMAC in more detail in the book?
=> docs: HMAC

.clabot
@pnmadelaine please approve this PR to make sure you've read the [CLA](https://github.com/cryspen/hacl-packages/blob/main/CLA.md).
It really only says that you are fine contributing under Apache 2.0/MIT.
=> Add pnmadelaine to CLA

docs/reference/requirements.txt
It seems that the latest release for `breathe` is broken.
Before locking the version, this is the error I got when running `pip install`:
```
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [1 lines of output]
error in breathe setup command: use_2to3 is invalid.
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
=> lock breathe version

.github/workflows/gh-pages.yml
v1.1.14 is 4b5ef36b314c2599664ca107bb8c02412548d79d.
I think I used the wrong ref before. From my understanding things should not break anymore. If so, I will revisit the fixations.
=> fix(ci): Use v1.1.14 of peaceiris/actions-mdbook.

docs/reference/hacl/hash/blake2/blake2b.md, tests/blake2b.cc
Work towards #193. BLAKE2b had higher priority IMO because we should have that in the documentation before the blog post.
=> docs: Add (tested) BLAKE2b example to API reference.

.github/workflows/build.yml, .github/workflows/build_pull_request.yml, .github/workflows/coverage.yml, .github/workflows/ocaml.yml, .github/workflows/rust.yml, .github/workflows/sanitizer_builds.yml
This closes #253.
Explanation:
GitHub Actions allows to define a concurrency group -- as a string -- for a workflow. Two workflow runs in the same group will be sequenced by default. By using `cancel-in-progress: true` we cancel the superseded ones instead. This is useful because, often, we commit small changes such as reviewer suggesstions in the review process. These additional commits spawn new workflow runs that run *in addition* to the (now superseded) pending workflow runs.
I propose to cancel these as fast as possible to make the CI more responsive and to not waste computing power.
By putting the workflow into the concurrency group with name ...
```yaml
group: ${{ github.workflow }}-${{ github.ref }}
```
... we make sure that a workflow "A" does not cancel a workflow "B". Thus, …
=> ci: Eagerly cancel superseded workflows.

.github/workflows/gh-pages.yml, .github/workflows/ocaml.yml
Try not setting `OPAMYES`, which might prompt opam to install system packages which are already present.
=> CI: Don't set OPAMYES

.github/workflows/gh-pages.yml, ocaml/hacl-star/hacl-star.opam, tools/doc.py
This avoids building and linking to the (non-existent) docs for `hacl-star-raw` on the [docs page](https://tech.cryspen.com/hacl-packages/ocaml/main/index.html)
=> OCaml: use --only-packages=hacl-star when building docs

.github/workflows/build.yml, .github/workflows/build_pull_request.yml, .github/workflows/ocaml.yml, .github/workflows/rust.yml, docs/book/src/developers/ci.md
Github is migrating macos-latest to macos-12 right now. https://github.com/actions/runner-images/issues/6384
The xcode version there (14) appears to have a linker bug https://stackoverflow.com/questions/73734125/xcode-14-0-gcc-12-linker-issue
The CI should be changed back to macos-latest when the bugs are resolved.
=> use macos-11 on CI for now

ocaml/Makefile
This PR removes HPKE from the OCaml bindings. They aren't used and aren't built correctly and generate undefined symbols in the library on some systems.
=> Block all of HPKE for ocaml

examples/cmake/CMakeLists.txt
This was pointing to the fixed version that's merged now.
Also: drop architecture from cmakelists.
=> use main in cmake example

tests/blake2b.cc
We do not use VLA in our CI (that checks all examples) and C does not have constant expressions. So... when we use a function like `Hacl_Hash_Definitions_hash_len(...)` (instead of `64` as best practice) the example needs to allocate memory at runtime. Which is... not so great. Which brings me to the point: We do need to introduce/cleanup HACL's identifiers.
=> docs: Update BLAKE2b example.

config/default_config.cmake, docs/reference/hacl/randomness/index.md, tests/drbg.cc
=> Refer to (new) `Hacl_HMAC_DRBG_free` and fix duplicate documentation.

docs/reference/hacl/aead/chacha20poly1305.md, docs/reference/hacl/hash/sha1.md, docs/reference/hacl/hash/sha2.md, docs/reference/hacl/hash/sha3.md, docs/reference/hacl/nacl/skae/index.md, docs/reference/hacl/signature/eddsa.md, tests/chacha20poly1305.cc, tests/ed25519.cc, tests/nacl.cc, tests/sha1.cc, tests/sha2.cc, tests/sha3.cc
This closes #285. Btw., this is the last issue I was assigned on that is part of the documentation milestone for HACL Packages 🎉 
(There are other documentation issues but nothing that we could tackle before the API redesign, IMO.)
=> docs: Switch to #defines in older examples. (+ minor fix)

.github/workflows/benchmark_pull_request.yml, tools/benchmark.py
This PR adds the `--compare` flag to the `./mach benchmark` subcommand, allowing to benchmark against another revision of hacl-packages.
It also adds a github action that will use that command on PRs and hacl-star branches, comparing them with `main`.
=> Benchmark pull requests against main

.github/workflows/examples.yml, docs/book/src/SUMMARY.md, docs/book/src/hacl-c/cmake.md
- Describe how to use HACL in a CMake project in the book.
- Run the cmake example on CI
No windows in CI for now (it's failing and needs debugging).
Fixes #268
=> Better integrate cmake example

.github/workflows/ocaml-docs.yml, docs/book/src/SUMMARY.md, docs/book/src/developers/ocaml-docs.md, docs/book/src/hacl-ocaml/readme.md
The book describes how to build ocaml docs for tags and where to add the links.
It's not fully automated. But I think this should be good enough for now as it's only needed for new releases (it could also be improved to build only new docs).
I can't test this until it's merged (deployment only works on main). But the [last job] worked as expected.
Fixes #227 
[last job]: https://github.com/cryspen/hacl-packages/actions/runs/3697819479
=> job to build docs for ocaml tags

.github/workflows/benchmark_pull_request.yml
`github.head_ref` only works when the action is triggered by a pull request, but the `benchmark_pull_request` action is also triggered by `hacl-star-**` branches, thus we need to use `github.ref` instead.
=> use `github.ref` instead of `github.head_ref`

CMakeLists.txt
Add support for consuming the build as part of other intermediate targets.
=> Add cmake config to export and install

tools/benchmark.py
Currently, the benchmark comparison workflow will fail every time we add a new benchmark, because it can't find it in the older repository.
This PR fixes the issue by only outputing a warning when a benchmark is missing in the older repository.
=> fix benchmark comparison

benchmarks/k256.cc, benchmarks/p256.cc
Also ensure nothing is optimised out (fixes weird p256 performance numbers).
=> drop asserts from benchmarks

.github/workflows/gh-pages.yml, docs/book/src/hacl-js/readme.md, docs/book/src/readme.md, js/doc/.gitignore, tools/doc.py
This PR updates the `gh-pages` workflow to also build the JS documentation.
It also updates the JS page in the mdbook.
Fixes #366
=> JavaScript Documentation

.github/workflows/gh-pages.yml, .github/workflows/ocaml.yml
This PR updates the `ocaml` and `gh-pages` workflows to use the [ocaml/setup-ocaml](https://github.com/marketplace/actions/set-up-ocaml) github action.
Doing so should avoid building ocaml on every run and reduce the execution time for these workflows.
Fixes #373
=> ci: use the ocaml/setup-ocaml github action

docs/reference/conf.py
@pnmadelaine reproduced and verified that this fixes the issue in a local docker container with the latest pip version.
Let's give this a try (as it is a good change anyway) but revalidate should we experience another break in the future.
=> docs: Use `navbar-logo.html` instead of `sidebar-logo.html`.

ocaml/hacl-star-raw.opam
Updates opam file with changes made during review on [ocaml/opam-repository](https://github.com/ocaml/opam-repository):
- specifies bytecode only not supported (can't build on s390x with OCaml 5) ([discussion](https://github.com/ocaml/opam-repository/pull/23551/commits/994ef5ef725b102032bdda15de72ccf2c47ae392#r1144713439))
- removes outdated CI exceptions ([discussion](https://github.com/ocaml/opam-repository/pull/22596#discussion_r1037381972))
=> OCaml API: update opam file for hacl-star-raw

benchmarks/blake.cc
In the Blake2 benchmarks, the streaming functions were ignoring `chunk_len` (=135) and instead using a chunk size of 7 for HACL/EverCrypt while using the right chunk size for OpenSSL, resulting in incomparable numbers. This PR fixes this issue by using `chunk_len` everywhere.
=> blake2 streaming benchmarks chunking fix

.github/workflows/build.yml, .github/workflows/build_pull_request.yml, mach, tools/openssl.py
Auto-detect openssl on macos
Also
- uses `ubuntu-latest` for CI
- drop old compilers (now: gcc 9-12, clang 11-14)
- benchmark with openssl on macos on ci
Fixes #399
=> Better openssl detection on macos

ocaml/hacl-star/Hacl.ml, ocaml/hacl-star/SharedDefs.ml, ocaml/hacl-star/tests/k256_test.ml
This MR contains:
- a fix for `Libsecp256k1.normalize_signature`, which, in addition to returning the normalized signature as an option, was also writing it in-place in the input buffer
- more precise testing for K-256 / libsecp256k1 signatures
=> OCaml API: small fix and test updates for K-256

README.md, docs/book/src/hacl-ocaml/readme.md, docs/reference/_templates/book.html, docs/reference/hacl/aead/chacha20poly1305.md, docs/reference/hacl/mac/index.md, ocaml/hacl-star-raw.opam, ocaml/hacl-star/hacl-star.opam
The domains changed and this should all go to the top level domain now.
=> change tech.cryspen.com to cryspen.com

js/package-lock.json, js/package.json
Release the npm package in order to restore compatibility with the OCaml `hacl-star` package version 0.7.1
=> hacl-wasm npm package: bump version to 1.4.0

ocaml/META
In ctypes < 0.21.0, the ctypes and ctypes.stubs libraries were installed in the same directory, so depending on one would make the other one visible.
ctypes 0.21.0 installs them in different directories so this makes it an error.
hacl-star-raw uses ctypes.stubs so the dependency should be recorded.
=> ocaml: fix compatibility with ctypes 0.21.0

.github/workflows/gh-pages.yml
This PR tries to fix the GitHub action deploying the documentation.
It currently fails on main, but I am unable to reproduce the error locally.
This PR also enables building the documentation (but not deploying it) on pull requests, to avoid bad surprises when merging in the future.
=> CI: fix documentation

benchmarks/sha3.cc, config/config.json, config/default_config.cmake, include/Hacl_Hash_SHA3_Scalar.h, include/Hacl_Hash_SHA3_Simd256.h, include/internal/Hacl_Hash_SHA3_Scalar.h, include/msvc/Hacl_Hash_SHA3_Scalar.h, include/msvc/Hacl_Hash_SHA3_Simd256.h, include/msvc/internal/Hacl_Hash_SHA3_Scalar.h, src/Hacl_Hash_SHA3_Scalar.c, src/Hacl_Hash_SHA3_Simd256.c, src/msvc/Hacl_Hash_SHA3_Scalar.c, src/msvc/Hacl_Hash_SHA3_Simd256.c, tests/sha3.cc
This patch uses the new hacl naming convention for SHA3 Scalar and Simd256 functions.
NOTE naming convention is slightly modified to distinguish between scalar and original SHA3 functions until we remove the latter.
=> Rename SHA3 Scalar and Simd256 functions

.github/workflows/gh-pages.yml
The workflow to build the documentation is currently flaky.
Pip sometimes fails with the following error:
```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement myst-parser (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for myst-parser (from -r requirements.txt (line 1))
```
Thus it seems that the macos runners sometimes come with Python 2 installed …
=> CI: ensure Python >=3 is installed when building the documentation

libcrux/include/eurydice_glue.h
+ Without this MSVC generates error C7555 when eurydice_glue.h is included in any C++ source (https://godbolt.org/z/EqcvcG3Yj)
=> Fix MSVC+CPP issue with including eurydice_glue.h w/ C++17
