.clabot
Readme.md

Here is a first draft of what the Readme could say? Shall we add more text consistent with our support contract document?

readme edits

---

.github/workflows/rust.yml
.gitignore
mach
rust/hacl-rust-sys/build.rs
tools/rust.py

This adds a ./mach rust subcommand to handle the standalone build and packaging

Use local C library for Rust packaging

---

tools/utils.py

Fix `check_cmd` by handling exception.

---

tests/chacha20poly1305.cc

This PR extends the test suite to cover Hacl_Chacha20_Vec32.c.

tests: Extend chacha20 tests.

---

config/config.json
tests/detection.cc

This test can be used to easily see which features are supported on the running machine. This is useful for CI as well as for troubleshooting.

tests: Add detection "pseudo" test.

---

.github/workflows/sanitizer_builds.yml
tests/drbg.cc

- fix leaks in drbg tests
- add sanitiser job to CI (fixes #124)

ci sanitizers

---

.github/workflows/ocaml.yml
.github/workflows/rust.yml

Don't run ocaml and rust workflow on irrelevant changes.

---

docs/src/developers/ci.md

Some small changes to the CI documentation to reflect recent changes.

reflect ci changes in documentation

---

.github/workflows/build.yml
.github/workflows/build_pull_request.yml
.github/workflows/sanitizer_builds.yml
README.md
docs/src/developers/ci.md
docs/src/developers/repo-overview.md

Disable c89 support.

---

docs/reference/evercrypt/aead/index.md
docs/reference/evercrypt/index.md
docs/reference/hacl/aead/aesgcm.md
docs/reference/hacl/aead/chacha20poly1305.md
docs/reference/hacl/aead/index.md
tests/chacha20poly1305.cc
tests/util.h

This PR adds some documentation for the AEAD part of HACL Packages.

docs: AEAD.

---

docs/reference/_static/css/custom.css
docs/reference/conf.py
docs/reference/evercrypt/hash/index.md
docs/reference/evercrypt/index.md
docs/reference/evercrypt/mac/index.md
docs/reference/hacl/hash/blake2/blake2b.md
docs/reference/hacl/hash/blake2/blake2s.md

Note: There is already documentation in hacl-star that will be used later.

docs: Blake2{b,s}

---

CONTRIBUTING.md
tools/update.py

- add docs to `CONTRIBUTING.md` for how to update the C code
- remove c89 from updates for now
cc @pnmadelaine

docs for how to update hacl packages from upstream

---

.github/workflows/gh-pages.yml

install dune on ci

---

CHANGELOG.md

1ec5b559c8e4fb80da31528236e2d34e5d689e7f is the initial commit.

Add an initial `CHANGELOG.md`.

---

docs/reference/index.md

docs: Add some welcome text.

---

.github/actions/upload_artifacts/action.yml
.github/workflows/build.yml
.github/workflows/build_pull_request.yml
.github/workflows/coverage.yml
.github/workflows/gh-pages.yml
.github/workflows/new_issue.yml
.github/workflows/ocaml.yml
.github/workflows/rust.yml
.github/workflows/sanitizer_builds.yml

This closes #239 and (IMO) also #84.

ci: Update actions.

---

.github/workflows/build.yml
.github/workflows/build_pull_request.yml
mach

build: Change `./mach install` flags.

---

docs/reference/hacl/aead/chacha20poly1305.md
docs/reference/hacl/mac/index.md

I can't reproduce locally but have a feeling that this may be it. The change itself is good, too, so it's worth a try.

docs: (Probably) fix broken tabs in Chacha20-Poly1305 and HMAC.

---

ocaml/META
ocaml/hacl-star-raw.opam
ocaml/hacl-star/CHANGES.md
ocaml/hacl-star/hacl-star.opam

Bump versions and add to changelog

OCaml: release 0.6.1

---

ocaml/META
ocaml/hacl-star-raw.opam
ocaml/hacl-star/CHANGES.md
ocaml/hacl-star/hacl-star.opam

Release new version containing new Vale snapshot, with fix https://github.com/hacl-star/hacl-star/pull/630

OCaml: release v0.6.2

---

docs/reference/hacl/hpke/index.md

docs: Add HPKE API docs.

---

docs/reference/hacl/hash/index.md
docs/reference/hacl/hash/sha1.md
docs/reference/hacl/hash/sha2.md
docs/reference/hacl/hash/sha3.md
tests/blake2b.cc
tests/blake2s.cc
tests/sha1.cc
tests/sha2.cc
tests/sha3.cc

docs: Make it clear that Streaming API allows to obtain intermediate digests.

---

docs/reference/hacl/dh/ec/curve25519.md
docs/reference/hacl/dh/ec/p256.md
docs/reference/hacl/kdf/index.md
docs/reference/hacl/mac/index.md
docs/reference/hacl/nacl/pkae/index.md
docs/reference/hacl/randomness/index.md
docs/reference/hacl/signature/ecdsa/k256.md
docs/reference/hacl/signature/ecdsa/p256.md
docs/reference/hacl/signature/rsapss.md
tests/drbg.cc
tests/hkdf.cc
tests/hmac.cc
tests/k256_ecdsa.cc
tests/nacl.cc
tests/p256_ecdh.cc
tests/p256_ecdsa.cc
tests/rsapss.cc
tests/util.h
tests/x25519.cc

This adds the remaining usage examples to the documentation. I tried to include asserts to catch errors in the examples. However, the work was a bit repetitive and I needed to copy&paste some code. So, please be aware that this PR was written less carefully. I can review again after a break before merging :-)

tests/docs: Add more examples to documentation.

---

tools/benchmark.py

finer performance regression tests

---

.github/workflows/gh-pages.yml
.github/workflows/ocaml.yml

Use latest pre-5.0.0 OCaml release

CI: bump OCaml version to 4.14.1

---

benchmarks/drbg.cc
config/config.json

As discussed, let's not care about the names too much. I opened https://github.com/cryspen/hacl-packages/issues/337 for that.

benchmarks: DRBG.

---

docs/book/src/SUMMARY.md
docs/book/src/developers/benchmarks.md

Here is an initial draft for the benchmark documentation. Does it go in the right direction? Anything else we should describe that is missing?

docs: Initial book page on benchmarking.

---

benchmarks/blake.cc
benchmarks/sha2.cc
benchmarks/sha3.cc
benchmarks/util.h

Add OpenSSL benchmarks for comparison.

OpenSSL benchmarks

---

docs/book/src/hacl-js/readme.md

This PR fixes a markdown typo introduced in #367

Fix documentation typo

---

.github/workflows/gh-pages.yml

This PR should fix the `gh-pages` workflow that was broken in #366

Fix the `gh-pages` workflow

---

.clabot

See #386. @pnmadelaine, could you review on behalf of Franziskus?

chore: Add `@mgstoyanov` to `.clabot`.

---

.github/workflows/gh-pages.yml
rust/src/hazmat/ed25519.rs

- hopefully fix doc deployment
- add keygen (secret to public) function for ed25519 to hazmat API

rust cleanup ctd.

---

CMakeLists.txt

Update test and benchmark dependencies.

bump gtest to 1.13 and benchmarks to main head

---

ocaml/hacl-star/EverCrypt.mli
ocaml/hacl-star/SharedDefs.ml
ocaml/hacl-star/tests/hash_test.ml

C snapshot change introduced with https://github.com/cryspen/hacl-packages/pull/405

OCaml API: add SHA-3 to EverCrypt hashing interface

---

.github/workflows/rust.yml
docs/book/src/hacl-rust/readme.md
mach
rust/Cargo.toml
rust/build.rs
rust/hacl-sys/Cargo.toml
rust/hacl-sys/build.rs
rust/hacl-sys/src/bindings/bindings.rs
tools/configure.py

Adding 32-bit Linux builds for Rust and Windows builds for.
Also, bump Rust versions to `0.0.3-pre.1`.

Rust 32-bit Linux, Windows 32 & 64 bit
